### PR TITLE
PPM Estimator date input

### PR DESCRIPTION
**Pull request by jamesatheyDDS**
## Checklist

I have…

- [x] run the application locally (`bin/rails server`) in a modern browser as well as in IE 11 and verified that my changes behave as expected.
- [x] run static code analysis (`bin/rubocop`) and vulnerability scan (`bin/brakeman`) against my changes.
- [x] run the test suite (`bin/rake spec`) and verified that all tests pass.
- [x] summarized below my changes and noted which issues (if any) this pull request fixes or addresses.
- [x] thoroughly outlined below the steps necessary to test my changes.
- [x] Attached screenshots showing the relevant pages both before and after my changes.

## Summary of Changes

According to the USWDS, date input should be done with three separate input fields, instead of `<input type="date">` which is not implemented in IE11 or macOS Safari, or with a JavaScript datepicker, which may not be 508 compliant, or work with form validation, etc.

This changeset therefore replaces the date input on the PPM Estimator page with three fields, and performs some extra client-side date validation, checking that the "day" field is valid for the supplied month and year (leap year aware!)

Also, this changeset scrolls the page so that the results or error is in view upon clicking submit.

## Testing

To verify the changes proposed in this pull request…

1. clone this repo,
1. git checkout `ppm-estimator-date-picker`,
1. set up development dependencies according to [CONTRIBUTING.md](https://github.com/deptofdefense/move.mil/blob/master/CONTRIBUTING.md),
1. run `bin/rails server`, and
1. load up [http://localhost:3000](http://localhost:3000) in the Web browser of your choice.

## Screenshots

<details><summary>Desktop Chrome - before</summary>

screen shot 2018-01-05 at 2 28 34 pm

</details>

<details><summary>Desktop Chrome - after</summary>

screen shot 2018-01-05 at 2 37 54 pm

</details>

<details><summary>Desktop IE11 - before</summary>

virtualbox_ie11 - win7_05_01_2018_14_37_12

</details>

<details><summary>Desktop IE11 - after</summary>

virtualbox_ie11 - win7_05_01_2018_14_38_46

</details>

<details><summary>Desktop Chrome - date validation error</summary>

screen shot 2018-01-05 at 2 39 20 pm

</details>

<details><summary>iOS Safari - before</summary>

img_25bed6bce88a-1

</details>

<details><summary>iOS Safari - after</summary>

img_07f5cbde8584-1

</details>

### CODE REVIEW

**Comment by lfantano** [comment]
The screenshot tabs don't show anything...

**Comment by jamesatheyDDS** [comment]
@lfantano I apologize for the delay. Screenshots are now in place.

**Comment by lfantano** [comment]
@jamesatheyDDS 

- The "For example" can we elaborate to say "For Example: January 18, 2018 should be entered as 1 18 2018.
- For the date validation error in chrome, is it possible display text in the same red saying that the date is invalid? If not, don't worry about it though.

Other than that - - looks great!

**Comment by jamesatheyDDS** [comment]
@lfantano Regarding "for example": like this?

screen shot 2018-01-05 at 2 58 38 pm

**Comment by lfantano** [comment]
Yep!

**Pull request merged**
